### ISSUE TITLE
Removing deactivated node

### ISSUE THREAD

**Issue by matejzero** [voxpupuli/puppet-prometheus_reporter#38]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.4.2
- Ruby: bundled
- Distribution: CentOS 7

## What are you seeing
When I remove a node via `puppet node deactivate` and `puppet cert clean <nodename>`, it is still reported by prometheus since this script doesn't remove orphaned nodes from `textfile_directory`.

## What behaviour did you expect instead
I was expecting that the script would remove the nodes that are no longer registered with puppet and this no need to report them.

**Comment by bastelfreak** [comment]
Hi @matejzero, thanks for pointing this out. Are you able to provide a patch for this? I'm not sure how the reporter can notice the `deactivate` command :thinking:

**Comment by matejzero** [comment]
That's a good point. Not what I think about it, I don't think that is possible. Current reporter only generates .prom files after a node sends a report, but nothing happens if the node is removed or deactivated.

To get that data, we would need to involve PuppetDB. I think I'll have to write a new exporter that pulls data from PuppetDB if I want to have that covered.
