### ISSUE TITLE
How does one deal with permissions?

### ISSUE THREAD

**Issue by robinbowes** [voxpupuli/puppet-prometheus_reporter#8]
I've installed the prometheus reporter and it's successfully producing reports in the designated directory. However, they are written with perms `0640` and owner/group by `puppet:puppet` and the node_exporter process, which is run as user `node-exporter`, is unable to read the files.

It doesn't seem right to add the node-exporter user to the `puppet` group.

Would it make sense to make the owner/group of the `.prom` files configurable?

**Comment by ralimi** [comment]
+1 for making this configurable.

In my case I hacked around this by running "echo 'umask 0022' >> /etc/default/puppetserver" before starting the puppet server. In my case that was sourced by the scripts that started the puppetserver soon after they did a 'umask 0027'.

It'd be great to undo that workaround.

**Comment by matejzero** [comment]
I've added a little bit of code to change chmod of file, since I didn't like the idea of whole puppet service running with umask 0027.

```
    File.open(filename, 'w') do |file|
-->   file.chmod(0644) 
      file.write(definitons)
      if File.exist?(yaml_filename)
```

Not the nicest solution, but it works as a quick workaround:)

**Comment by liqw33d** [comment]
This works for me:
```
  # files created by user $dropzone_user are group owned as 'node-exporter'
  $dropzone_user = 'puppet'
  file { '/var/lib/prometheus-dropzone':
    ensure => directory,
    owner  => $dropzone_user,
    group  => 'node-exporter',
    mode   => '2775',
  }
```
"prom" files are written as 'node-exporter' group so node_exporter can read them.

**Comment by anarcat** [comment]
could you make a symlink from (say) `/var/lib/prometheus-dropzone/puppet.prom` to somewhere the  Puppetmaster can write and use the `--report_filename` argument to point to that single file?
