### ISSUE TITLE
How to incorporate latest changes that aren't in Puppet Forge?

### ISSUE THREAD

**Issue by swilsonian** [voxpupuli/puppet-prometheus_reporter#81]
Hello!
Great module, but I'm curious as to why the latest version of this module is 1.1.0, [added to Puppet Forge on May 2nd 2021](https://forge.puppet.com/modules/puppet/prometheus_reporter/readme), but the readme and include significant options updates on May 28, 2024 ([caused by this PR](https://github.com/voxpupuli/puppet-prometheus_reporter/pull/77))?
Why is the latest version of the code not versioned or in puppet forge?

Should I be adding the module to my puppet server in a different way?
I prfer the manual installation method, aka, "puppet module install".

I could download directly to my environment modules folder, but according to Puppet Forge, when I select the Direct Download option, "Direct download is not typically how you would use a Puppet module to manage your infrastructure, but you may want to download the module in order to inspect the code." 
I have looked around but not seen anything in other Vox Populi github repos to lead me to a better strategy at the moment than downloading directly into my modules folder

Apologies if I'm missing something obvious. Thanks!

**Comment by techsk8** [comment]
You should use r10k to manage your puppet modules, it automates everything. In the end puppet is all about automation, why download its component modules manually. See more [here](https://www.puppet.com/docs/pe/2023.8/r10k.html) and [here](https://www.puppet.com/docs/pe/2023.8/puppetfile#managing_environment_content_with_puppetfiles). From these two links you can easily build yourself the automation you need through a `Puppetfile` and `r10k` to deploy your puppet code whether it's from internal or external sources, forge or github/gitlab. It will level up your entire puppet infrastructure.

Note that the links I provided are coming from Puppet Enterprise related documentation, but r10k is not at all limited to that specific puppet version, it is also available in the open source puppet, which is what I use. You can just install it on the puppetserver as a [gem](https://rubygems.org/gems/r10k).


Another way to manage your modules is through the [Code Manager](https://www.puppet.com/docs/pe/2023.8/code_mgr_how_it_works#moving_from_r10k_to_code_manager). You can read in the previous link what are its strengths and weaknesses. I'd prefer r10k anyway. It gives you way more control overall.

**Comment by TheMeier** [comment]
Yes r10k (or g10k) are recommended but that doe not help with the fact noone made a release for a long time. I will prepare one

**Comment by techsk8** [comment]
> Yes r10k (or g10k) are recommended but that doe not help with the fact none made a release for a long time. I will prepare one

That's right! And it happens quite often with many modules. I guess maintainers have only so many hours a week, like all of us, so things are left behind, hence why I often use the git version of the module

```ruby
mod 'apache',
  :git    => 'https://github.com/puppetlabs/puppetlabs-apache',
  :branch => 'main'
```

**Comment by TheMeier** [comment]
@techsk8 fair enough. I would still advise to use a commit id instead of the default branch to avoid nasty surprises in prodution.

**Comment by techsk8** [comment]
> @techsk8 fair enough. I would still advise to use a commit id instead of the default branch to avoid nasty surprises in prodution.
 you're right, I just took that example from puppetlabs docs.

**Comment by bastelfreak** [comment]
Hi, I published a new release
